/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.edu.prog2.BressanJoaquinSudarioRichard.vista;

import edu.ub.prog2.utils.AplicacioException;
import java.util.logging.Level;
import java.util.logging.Logger;
import ub.edu.prog2.BressanJoaquinSudarioRichard.controlador.Controlador;

/**
 *
 * @author joaqu
 */
public class AddFileLib extends javax.swing.JFrame {

    Controlador ctrl;
    String nomFile, codecFile, pathFile, camiImatge;
    float duration, fps1;
    int height, width, kbps1;

    /**
     * Creates new form AddFileLib
     */
    public AddFileLib(Controlador ctrl) {
        this.ctrl = ctrl;
        initComponents();
        this.addVideoPnl.setVisible(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        addVideoPnl = new javax.swing.JPanel();
        lblPath = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        lblNom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        lblCodec = new javax.swing.JLabel();
        txtCodec = new javax.swing.JTextField();
        lblDurada = new javax.swing.JLabel();
        txtDurada = new javax.swing.JTextField();
        lblAmplada = new javax.swing.JLabel();
        txtAmplada = new javax.swing.JTextField();
        lblAlcada = new javax.swing.JLabel();
        txtAlcada = new javax.swing.JTextField();
        lblFps = new javax.swing.JLabel();
        txtFps = new javax.swing.JTextField();
        btnAddVideo = new javax.swing.JButton();
        addAudioPnl = new javax.swing.JPanel();
        lblAudPath = new javax.swing.JLabel();
        txtAudPath = new javax.swing.JTextField();
        lblAudNom = new javax.swing.JLabel();
        txtAudNom = new javax.swing.JTextField();
        lblCodecNom = new javax.swing.JLabel();
        txtAudCodec = new javax.swing.JTextField();
        lblAudDurada = new javax.swing.JLabel();
        txtAudDurada = new javax.swing.JTextField();
        lblImagePath = new javax.swing.JLabel();
        txtAudImage = new javax.swing.JTextField();
        lblKbps = new javax.swing.JLabel();
        txtKbps = new javax.swing.JTextField();
        btnAddAudio = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Audio", "Video" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lblPath.setText("Path:");

        lblNom.setText("Nom:");

        lblCodec.setText("Codec:");

        lblDurada.setText("Durada:");

        lblAmplada.setText("Amplada:");

        lblAlcada.setText("Alcada:");

        lblFps.setText("FPS:");

        btnAddVideo.setText("Add Video");
        btnAddVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVideoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addVideoPnlLayout = new javax.swing.GroupLayout(addVideoPnl);
        addVideoPnl.setLayout(addVideoPnlLayout);
        addVideoPnlLayout.setHorizontalGroup(
            addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addVideoPnlLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addVideoPnlLayout.createSequentialGroup()
                        .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmplada)
                            .addComponent(lblAlcada)
                            .addComponent(lblFps))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAmplada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(txtAlcada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFps, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(addVideoPnlLayout.createSequentialGroup()
                        .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDurada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCodec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblNom)
                            .addComponent(lblPath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDurada)
                            .addComponent(txtNom)
                            .addComponent(txtPath)
                            .addComponent(txtCodec))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addVideoPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddVideo))
        );
        addVideoPnlLayout.setVerticalGroup(
            addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addVideoPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPath))
                .addGap(26, 26, 26)
                .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNom))
                .addGap(24, 24, 24)
                .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodec))
                .addGap(18, 18, 18)
                .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDurada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDurada))
                .addGap(18, 18, 18)
                .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmplada)
                    .addComponent(txtAmplada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlcada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlcada))
                .addGap(18, 18, 18)
                .addGroup(addVideoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddVideo))
        );

        lblAudPath.setText("Path:");

        lblAudNom.setText("Nom:");

        lblCodecNom.setText("Codec:");

        txtAudCodec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAudCodecActionPerformed(evt);
            }
        });

        lblAudDurada.setText("Durada:");

        lblImagePath.setText("Image path:");

        lblKbps.setText("KBPS:");

        btnAddAudio.setText("Add Audio");
        btnAddAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addAudioPnlLayout = new javax.swing.GroupLayout(addAudioPnl);
        addAudioPnl.setLayout(addAudioPnlLayout);
        addAudioPnlLayout.setHorizontalGroup(
            addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAudioPnlLayout.createSequentialGroup()
                .addGroup(addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addAudioPnlLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblAudDurada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCodecNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblAudNom)
                            .addComponent(lblAudPath)
                            .addComponent(lblImagePath)
                            .addComponent(lblKbps))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKbps, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(txtAudImage)
                            .addComponent(txtAudDurada)
                            .addComponent(txtAudNom)
                            .addComponent(txtAudPath)
                            .addComponent(txtAudCodec))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addAudioPnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddAudio)))
                .addContainerGap())
        );
        addAudioPnlLayout.setVerticalGroup(
            addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAudioPnlLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAudPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAudPath))
                .addGap(20, 20, 20)
                .addGroup(addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAudNom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAudNom))
                .addGap(18, 18, 18)
                .addGroup(addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAudCodec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodecNom))
                .addGap(18, 18, 18)
                .addGroup(addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAudDurada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAudDurada))
                .addGap(18, 18, 18)
                .addGroup(addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagePath)
                    .addComponent(txtAudImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addAudioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKbps)
                    .addComponent(txtKbps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddAudio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backBtn.setText("Go Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addVideoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34)
                        .addComponent(addAudioPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addAudioPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVideoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAudCodecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAudCodecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAudCodecActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (this.jComboBox1.getSelectedItem().equals("Video")) {
            this.addVideoPnl.setVisible(true);
            this.addAudioPnl.setVisible(false);
        } else {
            this.addVideoPnl.setVisible(false);
            this.addAudioPnl.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnAddVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVideoActionPerformed
        this.pathFile = this.txtPath.getText();
        this.nomFile = this.txtNom.getText();
        this.codecFile = this.txtCodec.getText();
        this.height = Integer.parseInt(this.txtAlcada.getText());
        this.width = Integer.parseInt(this.txtAmplada.getText());
        this.duration = Float.parseFloat(this.txtDurada.getText());
        this.fps1 = Float.parseFloat(this.txtFps.getText());
        try {
            this.ctrl.afegirVideo(pathFile, nomFile, codecFile, duration, height, width, fps1);
            dispose();
            GestioBiblioteca gb = new GestioBiblioteca(ctrl);
            gb.setLocationRelativeTo(null);
            gb.setVisible(true);
        } catch (AplicacioException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnAddVideoActionPerformed

    private void btnAddAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAudioActionPerformed
        this.pathFile = this.txtAudPath.getText();
        this.nomFile = this.txtAudNom.getText();
        this.codecFile = this.txtAudCodec.getText();
        this.camiImatge = this.txtAudImage.getText();
        this.duration = Float.parseFloat(this.txtAudDurada.getText());
        this.kbps1 = Integer.parseInt(this.txtKbps.getText());
        try {
            this.ctrl.afegirAudio(pathFile, camiImatge, nomFile, codecFile, duration, kbps1);
            dispose();
            GestioBiblioteca gb = new GestioBiblioteca(ctrl);
            gb.setLocationRelativeTo(null);
            gb.setVisible(true);
        } catch (AplicacioException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_btnAddAudioActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        dispose();
        GestioBiblioteca gestioLib = new GestioBiblioteca(this.ctrl);
        gestioLib.setLocationRelativeTo(null);
        gestioLib.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFileLib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFileLib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFileLib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFileLib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new AddFileLib().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addAudioPnl;
    private javax.swing.JPanel addVideoPnl;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnAddAudio;
    private javax.swing.JButton btnAddVideo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblAlcada;
    private javax.swing.JLabel lblAmplada;
    private javax.swing.JLabel lblAudDurada;
    private javax.swing.JLabel lblAudNom;
    private javax.swing.JLabel lblAudPath;
    private javax.swing.JLabel lblCodec;
    private javax.swing.JLabel lblCodecNom;
    private javax.swing.JLabel lblDurada;
    private javax.swing.JLabel lblFps;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JLabel lblKbps;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPath;
    private javax.swing.JTextField txtAlcada;
    private javax.swing.JTextField txtAmplada;
    private javax.swing.JTextField txtAudCodec;
    private javax.swing.JTextField txtAudDurada;
    private javax.swing.JTextField txtAudImage;
    private javax.swing.JTextField txtAudNom;
    private javax.swing.JTextField txtAudPath;
    private javax.swing.JTextField txtCodec;
    private javax.swing.JTextField txtDurada;
    private javax.swing.JTextField txtFps;
    private javax.swing.JTextField txtKbps;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
