/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.edu.prog2.BressanJoaquinSudarioRichard.vista;

import edu.ub.prog2.utils.AplicacioException;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import ub.edu.prog2.BressanJoaquinSudarioRichard.controlador.Controlador;

/**
 *
 * @author rsudarbe117.alumnes
 */
public class GestioAlbums extends javax.swing.JFrame {

    Controlador ctrl;

    /**
     * Creates new form GestioAlbums
     */
    public GestioAlbums(Controlador ctrl) {
        this.ctrl = ctrl;
        this.setResizable(false);
        initComponents();
        if (ctrl.isEmptyAlbums()) {
            this.deleteAlbumBtn.setEnabled(false);
            this.editAlbumBtn.setEnabled(false);
        }
        this.setFiles();
    }

    public void setFiles() {
        this.albumList.setModel(new AbstractListModel<String>() {
            List<String> l = ctrl.mostrarLlistatAlbums();

            @Override
            public int getSize() {
                return l.size();
            }

            @Override
            public String getElementAt(int index) {
                return l.get(index);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        albumList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        addAlbumBtn = new javax.swing.JButton();
        editAlbumBtn = new javax.swing.JButton();
        deleteAlbumBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(albumList);

        addAlbumBtn.setText("Add Album");
        addAlbumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlbumBtnActionPerformed(evt);
            }
        });

        editAlbumBtn.setText("Edit Album");
        editAlbumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAlbumBtnActionPerformed(evt);
            }
        });

        deleteAlbumBtn.setText("Delete Album");
        deleteAlbumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAlbumBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addAlbumBtn)
                .addGap(27, 27, 27)
                .addComponent(editAlbumBtn)
                .addGap(29, 29, 29)
                .addComponent(deleteAlbumBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAlbumBtn)
                    .addComponent(editAlbumBtn)
                    .addComponent(deleteAlbumBtn))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        backBtn.setText("Go Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        AplicacioUB4 mView = new AplicacioUB4(ctrl);
        mView.setVisible(true);
        mView.setLocationRelativeTo(null);
    }//GEN-LAST:event_backBtnActionPerformed

    private void editAlbumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAlbumBtnActionPerformed
        // TODO add your handling code here:
        if (!ctrl.isEmptyAlbums()) {
            String selected = albumList.getSelectedValue();
            selected = selected.substring(selected.indexOf("]") + 2);
            EditAlbum eAlbum = new EditAlbum(ctrl, ctrl.getActualAlbum(selected));
            eAlbum.setLocationRelativeTo(null);
            eAlbum.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Albums not found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editAlbumBtnActionPerformed

    private void addAlbumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAlbumBtnActionPerformed
        JTextField title = new JTextField(20);
        JTextField size = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Title:"));
        myPanel.add(title);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("Size:"));
        myPanel.add(size);

        int result = JOptionPane.showConfirmDialog(null, myPanel,
                "Please Enter X and Y Values", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            try {
                this.ctrl.afegirAlbum(title.getText(), Integer.parseInt(size.getText()));
            } catch (AplicacioException ex) {
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        this.editAlbumBtn.setEnabled(true);
        this.deleteAlbumBtn.setEnabled(true);
        this.setFiles();
    }//GEN-LAST:event_addAlbumBtnActionPerformed

    private void deleteAlbumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAlbumBtnActionPerformed
        // TODO add your handling code here:
        if (ctrl.isEmptyAlbums()) {
            JOptionPane.showMessageDialog(this,
                    "0 albums", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String selected = albumList.getSelectedValue();
            selected = selected.substring(selected.indexOf("[") + 1);
            selected = selected.substring(0, selected.indexOf("]"));
            int index = Integer.parseInt(selected);
            try {
                ctrl.esborrarFitxer(index - 1);
            } catch (AplicacioException ex) {
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (ctrl.isEmptyAlbums()) {
                this.deleteAlbumBtn.setEnabled(false);
            }
            this.setFiles();
        }
    }//GEN-LAST:event_deleteAlbumBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {*/
 /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestioAlbums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestioAlbums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestioAlbums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestioAlbums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
    //</editor-fold>

    /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestioAlbums().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAlbumBtn;
    private javax.swing.JList<String> albumList;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteAlbumBtn;
    private javax.swing.JButton editAlbumBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
