/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.edu.prog2.BressanJoaquinSudarioRichard.vista;

import edu.ub.prog2.utils.AplicacioException;
import ub.edu.prog2.BressanJoaquinSudarioRichard.controlador.Controlador;
 
/**
 *
 * @author joaqu
 */
public class GestioReproducció extends javax.swing.JFrame {
    Controlador ctrl;
    /**
     * Creates new form GestioReproducció
     */
    public GestioReproducció(Controlador ctrl) {
        initComponents();
        this.ctrl = ctrl;
        this.setLocation(0,472);
        this.ctrl.obrirFinestraReproductor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        mediaControlPanel = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        btnGoForward = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnRandom = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        isRandom = new javax.swing.JCheckBox();
        isContinu = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPlay.setText("❚❚");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnGoForward.setText("⏭");
        btnGoForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoForwardActionPerformed(evt);
            }
        });

        btnStop.setText("⏹");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnRandom.setText("🔀");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        btnContinue.setText("🔁");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        isRandom.setText("Reproduccio Aleatoria");
        isRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isRandomActionPerformed(evt);
            }
        });

        isContinu.setText("Reproduccio Continua");
        isContinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isContinuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mediaControlPanelLayout = new javax.swing.GroupLayout(mediaControlPanel);
        mediaControlPanel.setLayout(mediaControlPanelLayout);
        mediaControlPanelLayout.setHorizontalGroup(
            mediaControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mediaControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPlay)
                .addGap(18, 18, 18)
                .addComponent(btnStop)
                .addGap(18, 18, 18)
                .addComponent(btnGoForward)
                .addGap(18, 18, 18)
                .addComponent(btnRandom)
                .addGap(18, 18, 18)
                .addComponent(btnContinue)
                .addGap(18, 18, 18)
                .addGroup(mediaControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isRandom)
                    .addComponent(isContinu))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        mediaControlPanelLayout.setVerticalGroup(
            mediaControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mediaControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mediaControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlay)
                    .addComponent(btnStop)
                    .addComponent(btnGoForward)
                    .addComponent(btnRandom)
                    .addComponent(btnContinue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mediaControlPanelLayout.createSequentialGroup()
                .addComponent(isRandom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isContinu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(mediaControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mediaControlPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        if(this.btnPlay.getText().equals("❚❚")){
            try {
                this.ctrl.pausaReproduccio();
            } catch (AplicacioException ex) {
                System.out.println(ex);
            }
            this.btnPlay.setText("▶");
        }else{
            try {
                this.ctrl.reemprenReproduccio();
            } catch (AplicacioException ex) {
                System.out.println(ex);
            }
            this.btnPlay.setText("❚❚");
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        if (this.isContinu.isSelected()){
            this.isContinu.setSelected(false);
        }else{
            this.isContinu.setSelected(true);
        }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void isRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isRandomActionPerformed
        this.ctrl.setRandom(this.isRandom.isSelected());
    }//GEN-LAST:event_isRandomActionPerformed

    private void isContinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isContinuActionPerformed
        this.ctrl.setContinu(this.isContinu.isSelected());
    }//GEN-LAST:event_isContinuActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        if (this.isRandom.isSelected()){
            this.isRandom.setSelected(false);
        }else{
            this.isRandom.setSelected(true);
        }
    }//GEN-LAST:event_btnRandomActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        try {
            this.ctrl.aturaReproduccio();
        } catch (AplicacioException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnGoForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoForwardActionPerformed
        try {
            this.ctrl.saltaReproduccio();
        } catch (AplicacioException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnGoForwardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestioReproducció.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestioReproducció.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestioReproducció.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestioReproducció.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new GestioReproducció().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnGoForward;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnStop;
    private javax.swing.JCheckBox isContinu;
    private javax.swing.JCheckBox isRandom;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel mediaControlPanel;
    // End of variables declaration//GEN-END:variables
}
